### PR TITLE
Whale Lords

### PR DESCRIPTION
**Pull request by MasterLoopyBM**
The Whale Lords are immense in both size and wealth. Catching the three new types of Whale Lord will bring you much good wealth, and there are more on the way as well...

### CODE REVIEW

**Comment by Spiderlover** [comment]
cool, have they been tested?

**Comment by MasterLoopyBM** [comment]
They work. I caught the Beluga and the Baleen just today. Still have yet to hunt down Blue (thanks to a certain broken Magic Word. ~fish if you're wondering.)

**Comment by MasterLoopyBM** [comment]
Right now, the Whale Lord has the Piano Tuna model and the Holey Mackerel sounds as placeholders, so if SwagForeman wants to make a model for the Whale Lord, then he can. 😛

**Comment by Spiderlover** [comment]
cool :)

**Comment by SwagForeman** [comment]
I might do a model for the Whale Lord, but you would have to provide me with concept art.

**Comment by MasterLoopyBM** [comment]
whale lord concept
Does this work, SwagForeman?

**Comment by SwagForeman** [comment]
That works. I'm busy this week, though. Have a preferred animation?

**Comment by MasterLoopyBM** [comment]
Not sure exactly, I figure it would be somewhat elegant, though.

**Comment by SwagForeman** [comment]
whale lord
How does it look so far? Tomorrow I go to the beach, so I won't work on it anymore for the rest of the week.

**Comment by MasterLoopyBM** [comment]
Ooh, I like that. That'll work.

**Comment by SwagForeman** [comment]
I plan on having a red carpet roll out and have him swim up to the camera, then smile. Should he have white or gold teeth?

**Comment by MasterLoopyBM** [comment]
Hmmm, that might be a tough one to decide. Maybe all white with maybe one gold tooth that glimmers once he smiles?

**Pull request merged**
